# Generated by Django 4.2.4 on 2023-08-09 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyName',
            fields=[
                ('strategyname', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
