# Generated by Django 4.2.4 on 2023-08-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_question_recommended_time_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='starter_code',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
