# Generated by Django 4.2.4 on 2023-08-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_question_starter_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='score',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
